# Generated by Django 4.2.5 on 2023-09-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='code_parainage',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
