# Generated by Django 4.2.5 on 2023-09-04 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_code_parainage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_parrainage', models.DateTimeField(auto_now_add=True)),
                ('filleul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filleuls', to='student.student')),
                ('parrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrains', to='student.student')),
            ],
        ),
    ]
