# Generated by Django 4.2.5 on 2023-09-04 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_parrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to='student.student'),
        ),
        migrations.AlterField(
            model_name='parrain',
            name='filleul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filleul_parrains', to='student.student'),
        ),
    ]
