# Generated by Django 4.2.5 on 2023-09-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_parrain_alter_parrain_filleul'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parrain',
        ),
        migrations.AlterField(
            model_name='student',
            name='code_parainage',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
        migrations.DeleteModel(
            name='Parrain',
        ),
    ]
